export const PLANS = {
  free: {
    name: 'free',
    displayName: 'Free',
    emailsPerMonth: 10,
    scrapesPerMonth: 5,
    templates: 3,
    features: [
      '10 AI emails/month',
      '5 prospect scrapes',
      '3 templates',
      'Basic analytics',
    ],
    price: 0,
    priceAnnual: 0,
    stripePriceId: null,
  },
  starter: {
    name: 'starter',
    displayName: 'Starter',
    emailsPerMonth: 100,
    scrapesPerMonth: 50,
    templates: 10,
    features: [
      '100 AI emails/month',
      '50 prospect scrapes',
      '10 templates',
      'Advanced analytics',
      'Email history',
      'Priority support',
    ],
    price: 19,
    priceAnnual: 15,
    stripePriceId: process.env.STRIPE_STARTER_PRICE_ID || null,
  },
  pro: {
    name: 'pro',
    displayName: 'Pro',
    emailsPerMonth: 500,
    scrapesPerMonth: 200,
    templates: 'unlimited' as const,
    features: [
      '500 AI emails/month',
      '200 prospect scrapes',
      'Unlimited templates',
      'Advanced analytics',
      'Email history',
      'API access',
      'Team collaboration',
      'Priority support',
    ],
    price: 49,
    priceAnnual: 39,
    stripePriceId: process.env.STRIPE_PRO_PRICE_ID || null,
  },
} as const;
